# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Nov 27 01:52:25 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(826, 755)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 755))
        MainWindow.setMouseTracking(False)
        MainWindow.setToolTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_Main = QtGui.QHBoxLayout()
        self.horizontalLayout_Main.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_Main.setObjectName("horizontalLayout_Main")
        self.InputPotentialFlows_Dock = QtGui.QDockWidget(self.centralwidget)
        self.InputPotentialFlows_Dock.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPotentialFlows_Dock.sizePolicy().hasHeightForWidth())
        self.InputPotentialFlows_Dock.setSizePolicy(sizePolicy)
        self.InputPotentialFlows_Dock.setMinimumSize(QtCore.QSize(400, 551))
        self.InputPotentialFlows_Dock.setMaximumSize(QtCore.QSize(400, 524287))
        self.InputPotentialFlows_Dock.setAutoFillBackground(False)
        self.InputPotentialFlows_Dock.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InputPotentialFlows_Dock.setFloating(False)
        self.InputPotentialFlows_Dock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.InputPotentialFlows_Dock.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.InputPotentialFlows_Dock.setObjectName("InputPotentialFlows_Dock")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_potInput = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.tabWidget_potInput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_potInput.sizePolicy().hasHeightForWidth())
        self.tabWidget_potInput.setSizePolicy(sizePolicy)
        self.tabWidget_potInput.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget_potInput.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_potInput.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_potInput.setTabsClosable(False)
        self.tabWidget_potInput.setObjectName("tabWidget_potInput")
        self.tab_potInput = QtGui.QWidget()
        self.tab_potInput.setObjectName("tab_potInput")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_potInput)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_Source = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Source.setChecked(True)
        self.radioButton_Source.setObjectName("radioButton_Source")
        self.horizontalLayout_5.addWidget(self.radioButton_Source)
        self.radioButton_Sink = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Sink.setObjectName("radioButton_Sink")
        self.horizontalLayout_5.addWidget(self.radioButton_Sink)
        self.radioButton_Doublet = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Doublet.setObjectName("radioButton_Doublet")
        self.horizontalLayout_5.addWidget(self.radioButton_Doublet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_Vortex = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Vortex.setObjectName("radioButton_Vortex")
        self.horizontalLayout_6.addWidget(self.radioButton_Vortex)
        self.radioButton_UniformFlow = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_UniformFlow.setObjectName("radioButton_UniformFlow")
        self.horizontalLayout_6.addWidget(self.radioButton_UniformFlow)
        self.radioButton_potRandomElement = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_potRandomElement.setObjectName("radioButton_potRandomElement")
        self.horizontalLayout_6.addWidget(self.radioButton_potRandomElement)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_X = QtGui.QLabel(self.tab_potInput)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_14.addWidget(self.label_X)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.doubleSpinBox_FlowAngle_OR_X = QtGui.QDoubleSpinBox(self.tab_potInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_FlowAngle_OR_X.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_FlowAngle_OR_X.setSizePolicy(sizePolicy)
        self.doubleSpinBox_FlowAngle_OR_X.setMinimum(-10000.0)
        self.doubleSpinBox_FlowAngle_OR_X.setMaximum(10000.0)
        self.doubleSpinBox_FlowAngle_OR_X.setSingleStep(0.1)
        self.doubleSpinBox_FlowAngle_OR_X.setObjectName("doubleSpinBox_FlowAngle_OR_X")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_FlowAngle_OR_X)
        self.doubleSpinBox_Y = QtGui.QDoubleSpinBox(self.tab_potInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Y.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Y.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Y.setMinimum(-10000.0)
        self.doubleSpinBox_Y.setMaximum(10000.0)
        self.doubleSpinBox_Y.setSingleStep(0.1)
        self.doubleSpinBox_Y.setObjectName("doubleSpinBox_Y")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_Y)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_Strength = QtGui.QLabel(self.tab_potInput)
        self.label_Strength.setObjectName("label_Strength")
        self.horizontalLayout_17.addWidget(self.label_Strength)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.doubleSpinBox_Strength = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_Strength.setMinimum(-10000.0)
        self.doubleSpinBox_Strength.setMaximum(10000.0)
        self.doubleSpinBox_Strength.setSingleStep(0.1)
        self.doubleSpinBox_Strength.setObjectName("doubleSpinBox_Strength")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_Strength)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_Add = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.verticalLayout_8.addWidget(self.pushButton_Add)
        self.pushButton_Clear = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.verticalLayout_8.addWidget(self.pushButton_Clear)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_PathLines = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_PathLines.setChecked(True)
        self.radioButton_PathLines.setObjectName("radioButton_PathLines")
        self.horizontalLayout_7.addWidget(self.radioButton_PathLines)
        self.radioButton_StreamLines = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_StreamLines.setEnabled(True)
        self.radioButton_StreamLines.setChecked(False)
        self.radioButton_StreamLines.setObjectName("radioButton_StreamLines")
        self.horizontalLayout_7.addWidget(self.radioButton_StreamLines)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_pathLines = QtGui.QComboBox(self.tab_potInput)
        self.comboBox_pathLines.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_pathLines.setObjectName("comboBox_pathLines")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_pathLines)
        self.pushButton_potAddpatch = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_potAddpatch.setObjectName("pushButton_potAddpatch")
        self.verticalLayout_10.addWidget(self.pushButton_potAddpatch)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_center = QtGui.QLabel(self.tab_potInput)
        self.label_center.setObjectName("label_center")
        self.horizontalLayout.addWidget(self.label_center)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.doubleSpinBox_centerX = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_centerX.setMinimum(-10000.0)
        self.doubleSpinBox_centerX.setMaximum(10000.0)
        self.doubleSpinBox_centerX.setObjectName("doubleSpinBox_centerX")
        self.horizontalLayout.addWidget(self.doubleSpinBox_centerX)
        self.doubleSpinBox_centerY = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_centerY.setMinimum(-10000.0)
        self.doubleSpinBox_centerY.setMaximum(10000.0)
        self.doubleSpinBox_centerY.setObjectName("doubleSpinBox_centerY")
        self.horizontalLayout.addWidget(self.doubleSpinBox_centerY)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_patchInfo1 = QtGui.QLabel(self.tab_potInput)
        self.label_patchInfo1.setObjectName("label_patchInfo1")
        self.horizontalLayout_2.addWidget(self.label_patchInfo1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.doubleSpinBox_patchInfo1 = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_patchInfo1.setMinimum(-10000.0)
        self.doubleSpinBox_patchInfo1.setMaximum(10000.0)
        self.doubleSpinBox_patchInfo1.setObjectName("doubleSpinBox_patchInfo1")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_patchInfo1)
        self.doubleSpinBox_patchInfo2 = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_patchInfo2.setMinimum(-10000.0)
        self.doubleSpinBox_patchInfo2.setMaximum(10000.0)
        self.doubleSpinBox_patchInfo2.setObjectName("doubleSpinBox_patchInfo2")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_patchInfo2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.treeWidget_potElements = QtGui.QTreeWidget(self.tab_potInput)
        self.treeWidget_potElements.setTabKeyNavigation(True)
        self.treeWidget_potElements.setAlternatingRowColors(True)
        self.treeWidget_potElements.setObjectName("treeWidget_potElements")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        self.verticalLayout.addWidget(self.treeWidget_potElements)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Remove = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Remove.setEnabled(False)
        self.pushButton_Remove.setObjectName("pushButton_Remove")
        self.horizontalLayout_4.addWidget(self.pushButton_Remove)
        self.pushButton_Edit = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Edit.setEnabled(False)
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.horizontalLayout_4.addWidget(self.pushButton_Edit)
        self.pushButton_toggleSimulation = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_toggleSimulation.setEnabled(False)
        self.pushButton_toggleSimulation.setObjectName("pushButton_toggleSimulation")
        self.horizontalLayout_4.addWidget(self.pushButton_toggleSimulation)
        self.pushButton_Simulate = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Simulate.setObjectName("pushButton_Simulate")
        self.horizontalLayout_4.addWidget(self.pushButton_Simulate)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget_potInput.addTab(self.tab_potInput, "")
        self.tab_potOutputControl = QtGui.QWidget()
        self.tab_potOutputControl.setObjectName("tab_potOutputControl")
        self.tabWidget_potInput.addTab(self.tab_potOutputControl, "")
        self.verticalLayout_2.addWidget(self.tabWidget_potInput)
        self.InputPotentialFlows_Dock.setWidget(self.dockWidgetContents_3)
        self.horizontalLayout_Main.addWidget(self.InputPotentialFlows_Dock)
        self.InputCFD_Dock = QtGui.QDockWidget(self.centralwidget)
        self.InputCFD_Dock.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputCFD_Dock.sizePolicy().hasHeightForWidth())
        self.InputCFD_Dock.setSizePolicy(sizePolicy)
        self.InputCFD_Dock.setMinimumSize(QtCore.QSize(400, 675))
        self.InputCFD_Dock.setMaximumSize(QtCore.QSize(400, 524287))
        self.InputCFD_Dock.setAutoFillBackground(False)
        self.InputCFD_Dock.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InputCFD_Dock.setFloating(False)
        self.InputCFD_Dock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.InputCFD_Dock.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.InputCFD_Dock.setObjectName("InputCFD_Dock")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_cfdInput = QtGui.QTabWidget(self.dockWidgetContents_5)
        self.tabWidget_cfdInput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_cfdInput.sizePolicy().hasHeightForWidth())
        self.tabWidget_cfdInput.setSizePolicy(sizePolicy)
        self.tabWidget_cfdInput.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget_cfdInput.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_cfdInput.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_cfdInput.setTabsClosable(False)
        self.tabWidget_cfdInput.setObjectName("tabWidget_cfdInput")
        self.tab_potInput_2 = QtGui.QWidget()
        self.tab_potInput_2.setObjectName("tab_potInput_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_potInput_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_cfl = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfl.setObjectName("label_cfl")
        self.horizontalLayout_19.addWidget(self.label_cfl)
        self.doubleSpinBox_CFL = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_CFL.setDecimals(4)
        self.doubleSpinBox_CFL.setMinimum(0.0)
        self.doubleSpinBox_CFL.setMaximum(100000.0)
        self.doubleSpinBox_CFL.setSingleStep(0.1)
        self.doubleSpinBox_CFL.setProperty("value", 1.0)
        self.doubleSpinBox_CFL.setObjectName("doubleSpinBox_CFL")
        self.horizontalLayout_19.addWidget(self.doubleSpinBox_CFL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_cfdLength = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdLength.setObjectName("label_cfdLength")
        self.horizontalLayout_20.addWidget(self.label_cfdLength)
        self.doubleSpinBox_cfdLength = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdLength.setDecimals(6)
        self.doubleSpinBox_cfdLength.setMinimum(0.0)
        self.doubleSpinBox_cfdLength.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdLength.setSingleStep(1.0)
        self.doubleSpinBox_cfdLength.setProperty("value", 1.0)
        self.doubleSpinBox_cfdLength.setObjectName("doubleSpinBox_cfdLength")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_cfdLength)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_cfdDiaphramPosition = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdDiaphramPosition.setObjectName("label_cfdDiaphramPosition")
        self.horizontalLayout_21.addWidget(self.label_cfdDiaphramPosition)
        self.doubleSpinBox_cfdDiphrmPostn = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdDiphrmPostn.setDecimals(6)
        self.doubleSpinBox_cfdDiphrmPostn.setMinimum(0.0)
        self.doubleSpinBox_cfdDiphrmPostn.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdDiphrmPostn.setSingleStep(1.0)
        self.doubleSpinBox_cfdDiphrmPostn.setProperty("value", 0.5)
        self.doubleSpinBox_cfdDiphrmPostn.setObjectName("doubleSpinBox_cfdDiphrmPostn")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_cfdDiphrmPostn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_cfdNoOfCells = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdNoOfCells.setObjectName("label_cfdNoOfCells")
        self.horizontalLayout_22.addWidget(self.label_cfdNoOfCells)
        self.doubleSpinBox_cfdcellNum = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdcellNum.setDecimals(0)
        self.doubleSpinBox_cfdcellNum.setMinimum(1.0)
        self.doubleSpinBox_cfdcellNum.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdcellNum.setSingleStep(10.0)
        self.doubleSpinBox_cfdcellNum.setProperty("value", 100.0)
        self.doubleSpinBox_cfdcellNum.setObjectName("doubleSpinBox_cfdcellNum")
        self.horizontalLayout_22.addWidget(self.doubleSpinBox_cfdcellNum)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.label_uL_4 = QtGui.QLabel(self.tab_potInput_2)
        self.label_uL_4.setMidLineWidth(1)
        self.label_uL_4.setObjectName("label_uL_4")
        self.horizontalLayout_12.addWidget(self.label_uL_4)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.label_uL_8 = QtGui.QLabel(self.tab_potInput_2)
        self.label_uL_8.setMidLineWidth(1)
        self.label_uL_8.setObjectName("label_uL_8")
        self.horizontalLayout_12.addWidget(self.label_uL_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_uL_2 = QtGui.QLabel(self.tab_potInput_2)
        self.label_uL_2.setMidLineWidth(1)
        self.label_uL_2.setObjectName("label_uL_2")
        self.horizontalLayout_28.addWidget(self.label_uL_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem11)
        self.doubleSpinBox_cfduL = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfduL.setDecimals(4)
        self.doubleSpinBox_cfduL.setMinimum(-1000000000.0)
        self.doubleSpinBox_cfduL.setMaximum(1000000000.0)
        self.doubleSpinBox_cfduL.setSingleStep(10.0)
        self.doubleSpinBox_cfduL.setProperty("value", 0.0)
        self.doubleSpinBox_cfduL.setObjectName("doubleSpinBox_cfduL")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox_cfduL)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem12)
        self.doubleSpinBox_cfduR = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfduR.setDecimals(4)
        self.doubleSpinBox_cfduR.setMinimum(-999999999.0)
        self.doubleSpinBox_cfduR.setMaximum(1000000000.0)
        self.doubleSpinBox_cfduR.setSingleStep(10.0)
        self.doubleSpinBox_cfduR.setProperty("value", 0.0)
        self.doubleSpinBox_cfduR.setObjectName("doubleSpinBox_cfduR")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox_cfduR)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_cfdDiaphramPosition_15 = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdDiaphramPosition_15.setObjectName("label_cfdDiaphramPosition_15")
        self.horizontalLayout_46.addWidget(self.label_cfdDiaphramPosition_15)
        self.doubleSpinBox_cfdpresL = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdpresL.setMinimum(0.0)
        self.doubleSpinBox_cfdpresL.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdpresL.setSingleStep(100.0)
        self.doubleSpinBox_cfdpresL.setProperty("value", 1.0)
        self.doubleSpinBox_cfdpresL.setObjectName("doubleSpinBox_cfdpresL")
        self.horizontalLayout_46.addWidget(self.doubleSpinBox_cfdpresL)
        self.doubleSpinBox_cfdpresR = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdpresR.setMinimum(0.0)
        self.doubleSpinBox_cfdpresR.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdpresR.setSingleStep(100.0)
        self.doubleSpinBox_cfdpresR.setProperty("value", 0.1)
        self.doubleSpinBox_cfdpresR.setObjectName("doubleSpinBox_cfdpresR")
        self.horizontalLayout_46.addWidget(self.doubleSpinBox_cfdpresR)
        self.verticalLayout_7.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_cfdrhoL_4 = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdrhoL_4.setObjectName("label_cfdrhoL_4")
        self.horizontalLayout_45.addWidget(self.label_cfdrhoL_4)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem13)
        self.doubleSpinBox_cfdrhoL = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdrhoL.setDecimals(6)
        self.doubleSpinBox_cfdrhoL.setMinimum(0.0)
        self.doubleSpinBox_cfdrhoL.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdrhoL.setSingleStep(1.0)
        self.doubleSpinBox_cfdrhoL.setProperty("value", 1.0)
        self.doubleSpinBox_cfdrhoL.setObjectName("doubleSpinBox_cfdrhoL")
        self.horizontalLayout_45.addWidget(self.doubleSpinBox_cfdrhoL)
        self.doubleSpinBox_cfdrhoR = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdrhoR.setDecimals(6)
        self.doubleSpinBox_cfdrhoR.setMinimum(0.0)
        self.doubleSpinBox_cfdrhoR.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdrhoR.setSingleStep(1.0)
        self.doubleSpinBox_cfdrhoR.setProperty("value", 0.125)
        self.doubleSpinBox_cfdrhoR.setObjectName("doubleSpinBox_cfdrhoR")
        self.horizontalLayout_45.addWidget(self.doubleSpinBox_cfdrhoR)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_cfdtf = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdtf.setObjectName("label_cfdtf")
        self.horizontalLayout_48.addWidget(self.label_cfdtf)
        self.doubleSpinBox_cfdtf = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdtf.setDecimals(6)
        self.doubleSpinBox_cfdtf.setMinimum(0.0)
        self.doubleSpinBox_cfdtf.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdtf.setSingleStep(100.0)
        self.doubleSpinBox_cfdtf.setProperty("value", 0.5)
        self.doubleSpinBox_cfdtf.setObjectName("doubleSpinBox_cfdtf")
        self.horizontalLayout_48.addWidget(self.doubleSpinBox_cfdtf)
        self.verticalLayout_7.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_cfdDiaphramPosition_18 = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdDiaphramPosition_18.setObjectName("label_cfdDiaphramPosition_18")
        self.horizontalLayout_49.addWidget(self.label_cfdDiaphramPosition_18)
        self.doubleSpinBox_cfditrf = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfditrf.setDecimals(0)
        self.doubleSpinBox_cfditrf.setMinimum(0.0)
        self.doubleSpinBox_cfditrf.setMaximum(1000000000.0)
        self.doubleSpinBox_cfditrf.setSingleStep(100.0)
        self.doubleSpinBox_cfditrf.setProperty("value", 10.0)
        self.doubleSpinBox_cfditrf.setObjectName("doubleSpinBox_cfditrf")
        self.horizontalLayout_49.addWidget(self.doubleSpinBox_cfditrf)
        self.verticalLayout_7.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_cfdDiaphramPosition_19 = QtGui.QLabel(self.tab_potInput_2)
        self.label_cfdDiaphramPosition_19.setObjectName("label_cfdDiaphramPosition_19")
        self.horizontalLayout_50.addWidget(self.label_cfdDiaphramPosition_19)
        self.doubleSpinBox_cfdgamma = QtGui.QDoubleSpinBox(self.tab_potInput_2)
        self.doubleSpinBox_cfdgamma.setDecimals(6)
        self.doubleSpinBox_cfdgamma.setMinimum(0.0)
        self.doubleSpinBox_cfdgamma.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdgamma.setSingleStep(0.1)
        self.doubleSpinBox_cfdgamma.setProperty("value", 1.4)
        self.doubleSpinBox_cfdgamma.setObjectName("doubleSpinBox_cfdgamma")
        self.horizontalLayout_50.addWidget(self.doubleSpinBox_cfdgamma)
        self.verticalLayout_7.addLayout(self.horizontalLayout_50)
        self.pushButton_cfdSimulate = QtGui.QPushButton(self.tab_potInput_2)
        self.pushButton_cfdSimulate.setObjectName("pushButton_cfdSimulate")
        self.verticalLayout_7.addWidget(self.pushButton_cfdSimulate)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.tabWidget_cfdInput.addTab(self.tab_potInput_2, "")
        self.tab_potOutputControl_2 = QtGui.QWidget()
        self.tab_potOutputControl_2.setObjectName("tab_potOutputControl_2")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tab_potOutputControl_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.HLL = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.HLL.setCheckable(True)
        self.HLL.setChecked(False)
        self.HLL.setAutoRepeat(False)
        self.HLL.setObjectName("HLL")
        self.verticalLayout_16.addWidget(self.HLL)
        self.HLLC = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.HLLC.setObjectName("HLLC")
        self.verticalLayout_16.addWidget(self.HLLC)
        self.VanLeer = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.VanLeer.setChecked(True)
        self.VanLeer.setObjectName("VanLeer")
        self.verticalLayout_16.addWidget(self.VanLeer)
        self.StegerWarming = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.StegerWarming.setObjectName("StegerWarming")
        self.verticalLayout_16.addWidget(self.StegerWarming)
        self.radioButton_2 = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_16.addWidget(self.radioButton_2)
        self.AUSMp = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.AUSMp.setObjectName("AUSMp")
        self.verticalLayout_16.addWidget(self.AUSMp)
        self.AUSMUp = QtGui.QRadioButton(self.tab_potOutputControl_2)
        self.AUSMUp.setObjectName("AUSMUp")
        self.verticalLayout_16.addWidget(self.AUSMUp)
        self.verticalLayout_18.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_potOutputControl_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_cfdDiaphramPosition_14 = QtGui.QLabel(self.groupBox_3)
        self.label_cfdDiaphramPosition_14.setObjectName("label_cfdDiaphramPosition_14")
        self.horizontalLayout_41.addWidget(self.label_cfdDiaphramPosition_14)
        self.doubleSpinBox_cfdalpha = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cfdalpha.setMinimum(0.0)
        self.doubleSpinBox_cfdalpha.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdalpha.setSingleStep(100.0)
        self.doubleSpinBox_cfdalpha.setProperty("value", 0.19)
        self.doubleSpinBox_cfdalpha.setObjectName("doubleSpinBox_cfdalpha")
        self.horizontalLayout_41.addWidget(self.doubleSpinBox_cfdalpha)
        self.verticalLayout_19.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_uL_3 = QtGui.QLabel(self.groupBox_3)
        self.label_uL_3.setMidLineWidth(1)
        self.label_uL_3.setObjectName("label_uL_3")
        self.horizontalLayout_43.addWidget(self.label_uL_3)
        self.doubleSpinBox_cfdbeta = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cfdbeta.setDecimals(6)
        self.doubleSpinBox_cfdbeta.setMinimum(-999999999.0)
        self.doubleSpinBox_cfdbeta.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdbeta.setSingleStep(10.0)
        self.doubleSpinBox_cfdbeta.setProperty("value", 0.125)
        self.doubleSpinBox_cfdbeta.setObjectName("doubleSpinBox_cfdbeta")
        self.horizontalLayout_43.addWidget(self.doubleSpinBox_cfdbeta)
        self.verticalLayout_19.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_minfsq = QtGui.QLabel(self.groupBox_3)
        self.label_minfsq.setObjectName("label_minfsq")
        self.horizontalLayout_23.addWidget(self.label_minfsq)
        self.doubleSpinBox_cfdminfsq = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cfdminfsq.setDecimals(6)
        self.doubleSpinBox_cfdminfsq.setMinimum(0.0)
        self.doubleSpinBox_cfdminfsq.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdminfsq.setSingleStep(1.0)
        self.doubleSpinBox_cfdminfsq.setProperty("value", 0.0)
        self.doubleSpinBox_cfdminfsq.setObjectName("doubleSpinBox_cfdminfsq")
        self.horizontalLayout_23.addWidget(self.doubleSpinBox_cfdminfsq)
        self.verticalLayout_19.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_cfdku = QtGui.QLabel(self.groupBox_3)
        self.label_cfdku.setMidLineWidth(1)
        self.label_cfdku.setObjectName("label_cfdku")
        self.horizontalLayout_24.addWidget(self.label_cfdku)
        self.doubleSpinBox_cfdku = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cfdku.setDecimals(4)
        self.doubleSpinBox_cfdku.setMinimum(-1000000000.0)
        self.doubleSpinBox_cfdku.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdku.setSingleStep(10.0)
        self.doubleSpinBox_cfdku.setProperty("value", 0.75)
        self.doubleSpinBox_cfdku.setObjectName("doubleSpinBox_cfdku")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_cfdku)
        self.verticalLayout_19.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_cfdkp = QtGui.QLabel(self.groupBox_3)
        self.label_cfdkp.setObjectName("label_cfdkp")
        self.horizontalLayout_25.addWidget(self.label_cfdkp)
        self.doubleSpinBox_cfdkp = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cfdkp.setDecimals(4)
        self.doubleSpinBox_cfdkp.setMinimum(0.0)
        self.doubleSpinBox_cfdkp.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdkp.setSingleStep(100.0)
        self.doubleSpinBox_cfdkp.setProperty("value", 0.25)
        self.doubleSpinBox_cfdkp.setObjectName("doubleSpinBox_cfdkp")
        self.horizontalLayout_25.addWidget(self.doubleSpinBox_cfdkp)
        self.verticalLayout_19.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_cfdsigma = QtGui.QLabel(self.groupBox_3)
        self.label_cfdsigma.setObjectName("label_cfdsigma")
        self.horizontalLayout_42.addWidget(self.label_cfdsigma)
        self.doubleSpinBox_cfdsigma = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cfdsigma.setDecimals(6)
        self.doubleSpinBox_cfdsigma.setMinimum(-1000000000.0)
        self.doubleSpinBox_cfdsigma.setMaximum(1000000000.0)
        self.doubleSpinBox_cfdsigma.setSingleStep(1.0)
        self.doubleSpinBox_cfdsigma.setProperty("value", 1.0)
        self.doubleSpinBox_cfdsigma.setObjectName("doubleSpinBox_cfdsigma")
        self.horizontalLayout_42.addWidget(self.doubleSpinBox_cfdsigma)
        self.verticalLayout_19.addLayout(self.horizontalLayout_42)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addWidget(self.groupBox_3)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_16.addLayout(self.verticalLayout_18)
        self.tabWidget_cfdInput.addTab(self.tab_potOutputControl_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_cfl_3 = QtGui.QLabel(self.tab)
        self.label_cfl_3.setObjectName("label_cfl_3")
        self.horizontalLayout_63.addWidget(self.label_cfl_3)
        self.doubleSpinBox_advecCFL = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_advecCFL.setDecimals(4)
        self.doubleSpinBox_advecCFL.setMinimum(0.0)
        self.doubleSpinBox_advecCFL.setMaximum(100000.0)
        self.doubleSpinBox_advecCFL.setSingleStep(0.1)
        self.doubleSpinBox_advecCFL.setProperty("value", 1.0)
        self.doubleSpinBox_advecCFL.setObjectName("doubleSpinBox_advecCFL")
        self.horizontalLayout_63.addWidget(self.doubleSpinBox_advecCFL)
        self.verticalLayout_12.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_cfdNoOfCells_3 = QtGui.QLabel(self.tab)
        self.label_cfdNoOfCells_3.setObjectName("label_cfdNoOfCells_3")
        self.horizontalLayout_39.addWidget(self.label_cfdNoOfCells_3)
        self.doubleSpinBox_advecCellNum = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_advecCellNum.setDecimals(0)
        self.doubleSpinBox_advecCellNum.setMinimum(1.0)
        self.doubleSpinBox_advecCellNum.setMaximum(1000000000.0)
        self.doubleSpinBox_advecCellNum.setSingleStep(10.0)
        self.doubleSpinBox_advecCellNum.setProperty("value", 100.0)
        self.doubleSpinBox_advecCellNum.setObjectName("doubleSpinBox_advecCellNum")
        self.horizontalLayout_39.addWidget(self.doubleSpinBox_advecCellNum)
        self.verticalLayout_12.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_cfdDiaphramPosition_24 = QtGui.QLabel(self.tab)
        self.label_cfdDiaphramPosition_24.setObjectName("label_cfdDiaphramPosition_24")
        self.horizontalLayout_61.addWidget(self.label_cfdDiaphramPosition_24)
        self.doubleSpinBox_advecitrf = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_advecitrf.setDecimals(0)
        self.doubleSpinBox_advecitrf.setMinimum(0.0)
        self.doubleSpinBox_advecitrf.setMaximum(1000000000.0)
        self.doubleSpinBox_advecitrf.setSingleStep(100.0)
        self.doubleSpinBox_advecitrf.setProperty("value", 10.0)
        self.doubleSpinBox_advecitrf.setObjectName("doubleSpinBox_advecitrf")
        self.horizontalLayout_61.addWidget(self.doubleSpinBox_advecitrf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_cfdLength_3 = QtGui.QLabel(self.tab)
        self.label_cfdLength_3.setObjectName("label_cfdLength_3")
        self.horizontalLayout_40.addWidget(self.label_cfdLength_3)
        self.doubleSpinBox_advecLength = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_advecLength.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_advecLength.setSizePolicy(sizePolicy)
        self.doubleSpinBox_advecLength.setDecimals(6)
        self.doubleSpinBox_advecLength.setMinimum(0.0)
        self.doubleSpinBox_advecLength.setMaximum(1000000000.0)
        self.doubleSpinBox_advecLength.setSingleStep(1.0)
        self.doubleSpinBox_advecLength.setProperty("value", 1.0)
        self.doubleSpinBox_advecLength.setObjectName("doubleSpinBox_advecLength")
        self.horizontalLayout_40.addWidget(self.doubleSpinBox_advecLength)
        self.verticalLayout_12.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_62 = QtGui.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_cfdDiaphramPosition_25 = QtGui.QLabel(self.tab)
        self.label_cfdDiaphramPosition_25.setObjectName("label_cfdDiaphramPosition_25")
        self.horizontalLayout_62.addWidget(self.label_cfdDiaphramPosition_25)
        self.doubleSpinBox_advecC = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_advecC.setDecimals(6)
        self.doubleSpinBox_advecC.setMinimum(0.0)
        self.doubleSpinBox_advecC.setMaximum(1000000000.0)
        self.doubleSpinBox_advecC.setSingleStep(0.1)
        self.doubleSpinBox_advecC.setProperty("value", 1.0)
        self.doubleSpinBox_advecC.setObjectName("doubleSpinBox_advecC")
        self.horizontalLayout_62.addWidget(self.doubleSpinBox_advecC)
        self.verticalLayout_12.addLayout(self.horizontalLayout_62)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_advecSin = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_advecSin.setChecked(True)
        self.radioButton_advecSin.setObjectName("radioButton_advecSin")
        self.verticalLayout_13.addWidget(self.radioButton_advecSin)
        self.radioButton_stepUp = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_stepUp.setObjectName("radioButton_stepUp")
        self.verticalLayout_13.addWidget(self.radioButton_stepUp)
        self.radioButton_stepDown = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_stepDown.setObjectName("radioButton_stepDown")
        self.verticalLayout_13.addWidget(self.radioButton_stepDown)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout_15.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.radioButton_FTCS = QtGui.QRadioButton(self.groupBox)
        self.radioButton_FTCS.setCheckable(True)
        self.radioButton_FTCS.setChecked(True)
        self.radioButton_FTCS.setAutoRepeat(False)
        self.radioButton_FTCS.setObjectName("radioButton_FTCS")
        self.verticalLayout_14.addWidget(self.radioButton_FTCS)
        self.radioButton_FTFS = QtGui.QRadioButton(self.groupBox)
        self.radioButton_FTFS.setObjectName("radioButton_FTFS")
        self.verticalLayout_14.addWidget(self.radioButton_FTFS)
        self.radioButton_FTBS = QtGui.QRadioButton(self.groupBox)
        self.radioButton_FTBS.setCheckable(True)
        self.radioButton_FTBS.setChecked(False)
        self.radioButton_FTBS.setObjectName("radioButton_FTBS")
        self.verticalLayout_14.addWidget(self.radioButton_FTBS)
        self.radioButton_Upwind = QtGui.QRadioButton(self.groupBox)
        self.radioButton_Upwind.setObjectName("radioButton_Upwind")
        self.verticalLayout_14.addWidget(self.radioButton_Upwind)
        self.radioButton_LaxWendroff = QtGui.QRadioButton(self.groupBox)
        self.radioButton_LaxWendroff.setObjectName("radioButton_LaxWendroff")
        self.verticalLayout_14.addWidget(self.radioButton_LaxWendroff)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addWidget(self.groupBox)
        self.pushButton_advecSimulate = QtGui.QPushButton(self.tab)
        self.pushButton_advecSimulate.setObjectName("pushButton_advecSimulate")
        self.verticalLayout_15.addWidget(self.pushButton_advecSimulate)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem16)
        self.horizontalLayout_11.addLayout(self.verticalLayout_15)
        self.tabWidget_cfdInput.addTab(self.tab, "")
        self.verticalLayout_6.addWidget(self.tabWidget_cfdInput)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem17)
        self.InputCFD_Dock.setWidget(self.dockWidgetContents_5)
        self.horizontalLayout_Main.addWidget(self.InputCFD_Dock)
        self.verticalLayout_3.addLayout(self.horizontalLayout_Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        self.menu_Aerodynamics = QtGui.QMenu(self.menubar)
        self.menu_Aerodynamics.setObjectName("menu_Aerodynamics")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_Icons = QtGui.QToolBar(MainWindow)
        self.toolBar_Icons.setObjectName("toolBar_Icons")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Icons)
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Tools = QtGui.QAction(MainWindow)
        self.action_Tools.setObjectName("action_Tools")
        self.action_Potential_Flows = QtGui.QAction(MainWindow)
        self.action_Potential_Flows.setObjectName("action_Potential_Flows")
        self.actionPanel_Methods = QtGui.QAction(MainWindow)
        self.actionPanel_Methods.setObjectName("actionPanel_Methods")
        self.actionCFD = QtGui.QAction(MainWindow)
        self.actionCFD.setObjectName("actionCFD")
        self.action_Clear_all = QtGui.QAction(MainWindow)
        self.action_Clear_all.setObjectName("action_Clear_all")
        self.action_Clear_All = QtGui.QAction(MainWindow)
        self.action_Clear_All.setObjectName("action_Clear_All")
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Window.addAction(self.action_Clear_All)
        self.menu_Aerodynamics.addAction(self.action_Potential_Flows)
        self.menu_Aerodynamics.addAction(self.actionPanel_Methods)
        self.menu_Aerodynamics.addAction(self.actionCFD)
        self.menu_Aerodynamics.addSeparator()
        self.menu_Aerodynamics.addAction(self.action_Clear_all)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Aerodynamics.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.label_X.setBuddy(self.doubleSpinBox_Y)
        self.label_Strength.setBuddy(self.doubleSpinBox_Strength)
        self.label_patchInfo1.setBuddy(self.doubleSpinBox_patchInfo2)
        self.label_cfl.setBuddy(self.doubleSpinBox_CFL)
        self.label_cfdLength.setBuddy(self.doubleSpinBox_cfdLength)
        self.label_cfdDiaphramPosition.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdNoOfCells.setBuddy(self.doubleSpinBox_cfdcellNum)
        self.label_uL_4.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_uL_8.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_uL_2.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdDiaphramPosition_15.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdrhoL_4.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdtf.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdDiaphramPosition_18.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdDiaphramPosition_19.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdDiaphramPosition_14.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_uL_3.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_minfsq.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdku.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdkp.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdsigma.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfl_3.setBuddy(self.doubleSpinBox_CFL)
        self.label_cfdNoOfCells_3.setBuddy(self.doubleSpinBox_cfdcellNum)
        self.label_cfdDiaphramPosition_24.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)
        self.label_cfdLength_3.setBuddy(self.doubleSpinBox_cfdLength)
        self.label_cfdDiaphramPosition_25.setBuddy(self.doubleSpinBox_cfdDiphrmPostn)

        self.retranslateUi(MainWindow)
        self.tabWidget_potInput.setCurrentIndex(0)
        self.tabWidget_cfdInput.setCurrentIndex(1)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.actionCFD, QtCore.SIGNAL("activated()"), self.InputPotentialFlows_Dock.hide)
        QtCore.QObject.connect(self.actionCFD, QtCore.SIGNAL("activated()"), self.InputCFD_Dock.setFocus)
        QtCore.QObject.connect(self.action_Potential_Flows, QtCore.SIGNAL("activated()"), self.InputPotentialFlows_Dock.show)
        QtCore.QObject.connect(self.action_Potential_Flows, QtCore.SIGNAL("activated()"), self.InputPotentialFlows_Dock.setFocus)
        QtCore.QObject.connect(self.actionPanel_Methods, QtCore.SIGNAL("activated()"), self.InputPotentialFlows_Dock.show)
        QtCore.QObject.connect(self.actionPanel_Methods, QtCore.SIGNAL("activated()"), self.InputPotentialFlows_Dock.setFocus)
        QtCore.QObject.connect(self.action_Potential_Flows, QtCore.SIGNAL("activated()"), self.InputCFD_Dock.hide)
        QtCore.QObject.connect(self.actionCFD, QtCore.SIGNAL("activated()"), self.InputCFD_Dock.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_Source, self.radioButton_Sink)
        MainWindow.setTabOrder(self.radioButton_Sink, self.radioButton_Doublet)
        MainWindow.setTabOrder(self.radioButton_Doublet, self.radioButton_Vortex)
        MainWindow.setTabOrder(self.radioButton_Vortex, self.radioButton_UniformFlow)
        MainWindow.setTabOrder(self.radioButton_UniformFlow, self.radioButton_potRandomElement)
        MainWindow.setTabOrder(self.radioButton_potRandomElement, self.doubleSpinBox_FlowAngle_OR_X)
        MainWindow.setTabOrder(self.doubleSpinBox_FlowAngle_OR_X, self.doubleSpinBox_Y)
        MainWindow.setTabOrder(self.doubleSpinBox_Y, self.doubleSpinBox_Strength)
        MainWindow.setTabOrder(self.doubleSpinBox_Strength, self.pushButton_Add)
        MainWindow.setTabOrder(self.pushButton_Add, self.pushButton_Clear)
        MainWindow.setTabOrder(self.pushButton_Clear, self.radioButton_PathLines)
        MainWindow.setTabOrder(self.radioButton_PathLines, self.radioButton_StreamLines)
        MainWindow.setTabOrder(self.radioButton_StreamLines, self.comboBox_pathLines)
        MainWindow.setTabOrder(self.comboBox_pathLines, self.doubleSpinBox_centerX)
        MainWindow.setTabOrder(self.doubleSpinBox_centerX, self.doubleSpinBox_centerY)
        MainWindow.setTabOrder(self.doubleSpinBox_centerY, self.doubleSpinBox_patchInfo1)
        MainWindow.setTabOrder(self.doubleSpinBox_patchInfo1, self.doubleSpinBox_patchInfo2)
        MainWindow.setTabOrder(self.doubleSpinBox_patchInfo2, self.pushButton_potAddpatch)
        MainWindow.setTabOrder(self.pushButton_potAddpatch, self.pushButton_Simulate)
        MainWindow.setTabOrder(self.pushButton_Simulate, self.treeWidget_potElements)
        MainWindow.setTabOrder(self.treeWidget_potElements, self.pushButton_Edit)
        MainWindow.setTabOrder(self.pushButton_Edit, self.pushButton_Remove)
        MainWindow.setTabOrder(self.pushButton_Remove, self.pushButton_toggleSimulation)
        MainWindow.setTabOrder(self.pushButton_toggleSimulation, self.tabWidget_potInput)
        MainWindow.setTabOrder(self.tabWidget_potInput, self.doubleSpinBox_CFL)
        MainWindow.setTabOrder(self.doubleSpinBox_CFL, self.doubleSpinBox_cfdLength)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdLength, self.doubleSpinBox_cfdDiphrmPostn)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdDiphrmPostn, self.doubleSpinBox_cfdcellNum)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdcellNum, self.doubleSpinBox_cfduL)
        MainWindow.setTabOrder(self.doubleSpinBox_cfduL, self.doubleSpinBox_cfdpresR)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdpresR, self.doubleSpinBox_cfdrhoR)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdrhoR, self.doubleSpinBox_cfdtf)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdtf, self.doubleSpinBox_cfditrf)
        MainWindow.setTabOrder(self.doubleSpinBox_cfditrf, self.doubleSpinBox_cfdgamma)
        MainWindow.setTabOrder(self.doubleSpinBox_cfdgamma, self.HLLC)
        MainWindow.setTabOrder(self.HLLC, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.AUSMUp)
        MainWindow.setTabOrder(self.AUSMUp, self.VanLeer)
        MainWindow.setTabOrder(self.VanLeer, self.AUSMp)
        MainWindow.setTabOrder(self.AUSMp, self.HLL)
        MainWindow.setTabOrder(self.HLL, self.StegerWarming)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EduAeroSpace", None, QtGui.QApplication.UnicodeUTF8))
        self.InputPotentialFlows_Dock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Potential flows", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Source.setText(QtGui.QApplication.translate("MainWindow", "&Source", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Sink.setText(QtGui.QApplication.translate("MainWindow", "S&ink", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Doublet.setText(QtGui.QApplication.translate("MainWindow", "&Doublet", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Vortex.setText(QtGui.QApplication.translate("MainWindow", "&Vortex", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_UniformFlow.setText(QtGui.QApplication.translate("MainWindow", "&Uniform flow", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_potRandomElement.setText(QtGui.QApplication.translate("MainWindow", "&Random", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("MainWindow", "(X, Y)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Strength.setText(QtGui.QApplication.translate("MainWindow", "Strength", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Add.setText(QtGui.QApplication.translate("MainWindow", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_PathLines.setText(QtGui.QApplication.translate("MainWindow", "&Path lines", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_StreamLines.setText(QtGui.QApplication.translate("MainWindow", "&Stream lines", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(0, QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(1, QtGui.QApplication.translate("MainWindow", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(2, QtGui.QApplication.translate("MainWindow", "Rectangular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(3, QtGui.QApplication.translate("MainWindow", "Line at X", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(4, QtGui.QApplication.translate("MainWindow", "Line at Y", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(5, QtGui.QApplication.translate("MainWindow", "Elliptical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(6, QtGui.QApplication.translate("MainWindow", "Parabolic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(7, QtGui.QApplication.translate("MainWindow", "Hyperbolic", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_potAddpatch.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_center.setText(QtGui.QApplication.translate("MainWindow", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_patchInfo1.setText(QtGui.QApplication.translate("MainWindow", "(X, Y)", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Added Elements", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_potElements.isSortingEnabled()
        self.treeWidget_potElements.setSortingEnabled(False)
        self.treeWidget_potElements.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Doublets", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Sinks", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Uniformflow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "Vortices", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.setSortingEnabled(__sortingEnabled)
        self.pushButton_Remove.setText(QtGui.QApplication.translate("MainWindow", "&Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Edit.setText(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_toggleSimulation.setText(QtGui.QApplication.translate("MainWindow", "&Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Simulate.setText(QtGui.QApplication.translate("MainWindow", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_potInput.setTabText(self.tabWidget_potInput.indexOf(self.tab_potInput), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_potInput.setTabText(self.tabWidget_potInput.indexOf(self.tab_potOutputControl), QtGui.QApplication.translate("MainWindow", "Output Control", None, QtGui.QApplication.UnicodeUTF8))
        self.InputCFD_Dock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CFD Shock Tube Simulations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfl.setText(QtGui.QApplication.translate("MainWindow", "CFL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdLength.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition.setText(QtGui.QApplication.translate("MainWindow", "Diagphram Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdNoOfCells.setText(QtGui.QApplication.translate("MainWindow", "Number Of Cells:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_uL_4.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_uL_8.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_uL_2.setText(QtGui.QApplication.translate("MainWindow", "Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition_15.setText(QtGui.QApplication.translate("MainWindow", "Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdrhoL_4.setText(QtGui.QApplication.translate("MainWindow", "Density", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdtf.setText(QtGui.QApplication.translate("MainWindow", "Final Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition_18.setText(QtGui.QApplication.translate("MainWindow", "No. of Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition_19.setText(QtGui.QApplication.translate("MainWindow", "gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cfdSimulate.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_cfdInput.setTabText(self.tabWidget_cfdInput.indexOf(self.tab_potInput_2), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.HLL.setText(QtGui.QApplication.translate("MainWindow", "HLL", None, QtGui.QApplication.UnicodeUTF8))
        self.HLLC.setText(QtGui.QApplication.translate("MainWindow", "HLLC", None, QtGui.QApplication.UnicodeUTF8))
        self.VanLeer.setText(QtGui.QApplication.translate("MainWindow", "VanLeer", None, QtGui.QApplication.UnicodeUTF8))
        self.StegerWarming.setText(QtGui.QApplication.translate("MainWindow", "StegerWarming", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "AUSM", None, QtGui.QApplication.UnicodeUTF8))
        self.AUSMp.setText(QtGui.QApplication.translate("MainWindow", "AUSM+", None, QtGui.QApplication.UnicodeUTF8))
        self.AUSMUp.setText(QtGui.QApplication.translate("MainWindow", "AUSM+Up", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition_14.setText(QtGui.QApplication.translate("MainWindow", "alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_uL_3.setText(QtGui.QApplication.translate("MainWindow", "beta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_minfsq.setText(QtGui.QApplication.translate("MainWindow", "minfsq", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdku.setText(QtGui.QApplication.translate("MainWindow", "ku", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdkp.setText(QtGui.QApplication.translate("MainWindow", "kp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdsigma.setText(QtGui.QApplication.translate("MainWindow", "sigma", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_cfdInput.setTabText(self.tabWidget_cfdInput.indexOf(self.tab_potOutputControl_2), QtGui.QApplication.translate("MainWindow", "Output Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfl_3.setText(QtGui.QApplication.translate("MainWindow", "CFL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdNoOfCells_3.setText(QtGui.QApplication.translate("MainWindow", "Number Of Cells:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition_24.setText(QtGui.QApplication.translate("MainWindow", "No. of Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdLength_3.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cfdDiaphramPosition_25.setText(QtGui.QApplication.translate("MainWindow", "c(of u_t + c u_x=0)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_advecSin.setText(QtGui.QApplication.translate("MainWindow", "Sin", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_stepUp.setText(QtGui.QApplication.translate("MainWindow", "Step Up", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_stepDown.setText(QtGui.QApplication.translate("MainWindow", "Step Down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_FTCS.setText(QtGui.QApplication.translate("MainWindow", "FTCS", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_FTFS.setText(QtGui.QApplication.translate("MainWindow", "FTFS", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_FTBS.setText(QtGui.QApplication.translate("MainWindow", "FTBS", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Upwind.setText(QtGui.QApplication.translate("MainWindow", "Upwind", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_LaxWendroff.setText(QtGui.QApplication.translate("MainWindow", "LaxWendroff", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_advecSimulate.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_cfdInput.setTabText(self.tabWidget_cfdInput.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Advection", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(QtGui.QApplication.translate("MainWindow", "&Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Aerodynamics.setTitle(QtGui.QApplication.translate("MainWindow", "&Aerodynamics", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Icons.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Tools.setText(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Potential_Flows.setText(QtGui.QApplication.translate("MainWindow", "&Potential Flows", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPanel_Methods.setText(QtGui.QApplication.translate("MainWindow", "Panel Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCFD.setText(QtGui.QApplication.translate("MainWindow", "CFD", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clear_all.setText(QtGui.QApplication.translate("MainWindow", "&Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clear_All.setText(QtGui.QApplication.translate("MainWindow", "&Clear All", None, QtGui.QApplication.UnicodeUTF8))

