# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Tue Nov  8 07:45:57 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1071, 662)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setToolTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_Main = QtGui.QHBoxLayout()
        self.horizontalLayout_Main.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_Main.setObjectName("horizontalLayout_Main")
        self.Input_Dock = QtGui.QDockWidget(self.centralwidget)
        self.Input_Dock.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Dock.sizePolicy().hasHeightForWidth())
        self.Input_Dock.setSizePolicy(sizePolicy)
        self.Input_Dock.setMinimumSize(QtCore.QSize(400, 423))
        self.Input_Dock.setMaximumSize(QtCore.QSize(400, 524287))
        self.Input_Dock.setAutoFillBackground(False)
        self.Input_Dock.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Input_Dock.setFloating(False)
        self.Input_Dock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.Input_Dock.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.Input_Dock.setObjectName("Input_Dock")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_potInput = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.tabWidget_potInput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_potInput.sizePolicy().hasHeightForWidth())
        self.tabWidget_potInput.setSizePolicy(sizePolicy)
        self.tabWidget_potInput.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget_potInput.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_potInput.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_potInput.setTabsClosable(False)
        self.tabWidget_potInput.setObjectName("tabWidget_potInput")
        self.tab_potInput = QtGui.QWidget()
        self.tab_potInput.setObjectName("tab_potInput")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_potInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_potElements = QtGui.QTreeWidget(self.tab_potInput)
        self.treeWidget_potElements.setTabKeyNavigation(True)
        self.treeWidget_potElements.setAlternatingRowColors(True)
        self.treeWidget_potElements.setObjectName("treeWidget_potElements")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_potElements)
        self.verticalLayout.addWidget(self.treeWidget_potElements)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Remove = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Remove.setEnabled(False)
        self.pushButton_Remove.setObjectName("pushButton_Remove")
        self.horizontalLayout_4.addWidget(self.pushButton_Remove)
        self.pushButton_Edit = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Edit.setEnabled(False)
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.horizontalLayout_4.addWidget(self.pushButton_Edit)
        self.pushButton_toggleSimulation = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_toggleSimulation.setEnabled(False)
        self.pushButton_toggleSimulation.setObjectName("pushButton_toggleSimulation")
        self.horizontalLayout_4.addWidget(self.pushButton_toggleSimulation)
        self.pushButton_Simulate = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Simulate.setObjectName("pushButton_Simulate")
        self.horizontalLayout_4.addWidget(self.pushButton_Simulate)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_Source = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Source.setChecked(True)
        self.radioButton_Source.setObjectName("radioButton_Source")
        self.horizontalLayout_5.addWidget(self.radioButton_Source)
        self.radioButton_Sink = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Sink.setObjectName("radioButton_Sink")
        self.horizontalLayout_5.addWidget(self.radioButton_Sink)
        self.radioButton_Doublet = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Doublet.setObjectName("radioButton_Doublet")
        self.horizontalLayout_5.addWidget(self.radioButton_Doublet)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_Vortex = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_Vortex.setObjectName("radioButton_Vortex")
        self.horizontalLayout_6.addWidget(self.radioButton_Vortex)
        self.radioButton_UniformFlow = QtGui.QRadioButton(self.tab_potInput)
        self.radioButton_UniformFlow.setObjectName("radioButton_UniformFlow")
        self.horizontalLayout_6.addWidget(self.radioButton_UniformFlow)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_X = QtGui.QLabel(self.tab_potInput)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout_14.addWidget(self.label_X)
        self.doubleSpinBox_X = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_X.setMinimum(-1000.0)
        self.doubleSpinBox_X.setMaximum(1000.0)
        self.doubleSpinBox_X.setSingleStep(0.1)
        self.doubleSpinBox_X.setObjectName("doubleSpinBox_X")
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_X)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_Y = QtGui.QLabel(self.tab_potInput)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_15.addWidget(self.label_Y)
        self.doubleSpinBox_Y = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_Y.setMinimum(-1000.0)
        self.doubleSpinBox_Y.setMaximum(1000.0)
        self.doubleSpinBox_Y.setSingleStep(0.1)
        self.doubleSpinBox_Y.setObjectName("doubleSpinBox_Y")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_Y)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_FlowAngle = QtGui.QLabel(self.tab_potInput)
        self.label_FlowAngle.setObjectName("label_FlowAngle")
        self.horizontalLayout_16.addWidget(self.label_FlowAngle)
        self.doubleSpinBox_FlowAngle = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_FlowAngle.setMinimum(-360.0)
        self.doubleSpinBox_FlowAngle.setMaximum(360.0)
        self.doubleSpinBox_FlowAngle.setSingleStep(1.0)
        self.doubleSpinBox_FlowAngle.setObjectName("doubleSpinBox_FlowAngle")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_FlowAngle)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_Strength = QtGui.QLabel(self.tab_potInput)
        self.label_Strength.setObjectName("label_Strength")
        self.horizontalLayout_17.addWidget(self.label_Strength)
        self.doubleSpinBox_Strength = QtGui.QDoubleSpinBox(self.tab_potInput)
        self.doubleSpinBox_Strength.setMinimum(-10000.0)
        self.doubleSpinBox_Strength.setMaximum(10000.0)
        self.doubleSpinBox_Strength.setSingleStep(0.1)
        self.doubleSpinBox_Strength.setObjectName("doubleSpinBox_Strength")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_Strength)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.pushButton_Clear = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.horizontalLayout_18.addWidget(self.pushButton_Clear)
        self.pushButton_Add = QtGui.QPushButton(self.tab_potInput)
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.horizontalLayout_18.addWidget(self.pushButton_Add)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.tabWidget_potInput.addTab(self.tab_potInput, "")
        self.tab_potOutputControl = QtGui.QWidget()
        self.tab_potOutputControl.setObjectName("tab_potOutputControl")
        self.frame_patchInput = QtGui.QFrame(self.tab_potOutputControl)
        self.frame_patchInput.setEnabled(True)
        self.frame_patchInput.setGeometry(QtCore.QRect(20, 50, 331, 131))
        self.frame_patchInput.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_patchInput.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_patchInput.setObjectName("frame_patchInput")
        self.layoutWidget = QtGui.QWidget(self.frame_patchInput)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_pathLines = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_pathLines.setObjectName("comboBox_pathLines")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.comboBox_pathLines.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_pathLines)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_center = QtGui.QLabel(self.layoutWidget)
        self.label_center.setObjectName("label_center")
        self.horizontalLayout.addWidget(self.label_center)
        self.doubleSpinBox_centerX = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_centerX.setObjectName("doubleSpinBox_centerX")
        self.horizontalLayout.addWidget(self.doubleSpinBox_centerX)
        self.doubleSpinBox_centerY = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_centerY.setObjectName("doubleSpinBox_centerY")
        self.horizontalLayout.addWidget(self.doubleSpinBox_centerY)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_patchInfo1 = QtGui.QLabel(self.layoutWidget)
        self.label_patchInfo1.setObjectName("label_patchInfo1")
        self.horizontalLayout_2.addWidget(self.label_patchInfo1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.doubleSpinBox_patchInfo1 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_patchInfo1.setObjectName("doubleSpinBox_patchInfo1")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_patchInfo1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_patchInfo2 = QtGui.QLabel(self.layoutWidget)
        self.label_patchInfo2.setObjectName("label_patchInfo2")
        self.horizontalLayout_2.addWidget(self.label_patchInfo2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.doubleSpinBox_patchInfo2 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_patchInfo2.setObjectName("doubleSpinBox_patchInfo2")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_patchInfo2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(self.tab_potOutputControl)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 311, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_PathLines = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_PathLines.setChecked(True)
        self.radioButton_PathLines.setObjectName("radioButton_PathLines")
        self.horizontalLayout_7.addWidget(self.radioButton_PathLines)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.radioButton_StreamLines = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_StreamLines.setEnabled(True)
        self.radioButton_StreamLines.setChecked(False)
        self.radioButton_StreamLines.setObjectName("radioButton_StreamLines")
        self.horizontalLayout_7.addWidget(self.radioButton_StreamLines)
        self.tabWidget_potInput.addTab(self.tab_potOutputControl, "")
        self.verticalLayout_2.addWidget(self.tabWidget_potInput)
        self.Input_Dock.setWidget(self.dockWidgetContents_3)
        self.horizontalLayout_Main.addWidget(self.Input_Dock)
        self.verticalLayout_3.addLayout(self.horizontalLayout_Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        self.menu_Aerodynamics = QtGui.QMenu(self.menubar)
        self.menu_Aerodynamics.setObjectName("menu_Aerodynamics")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_Icons = QtGui.QToolBar(MainWindow)
        self.toolBar_Icons.setObjectName("toolBar_Icons")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Icons)
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Tools = QtGui.QAction(MainWindow)
        self.action_Tools.setObjectName("action_Tools")
        self.action_Potential_Flows = QtGui.QAction(MainWindow)
        self.action_Potential_Flows.setObjectName("action_Potential_Flows")
        self.actionPanel_Methods = QtGui.QAction(MainWindow)
        self.actionPanel_Methods.setObjectName("actionPanel_Methods")
        self.actionCFD = QtGui.QAction(MainWindow)
        self.actionCFD.setObjectName("actionCFD")
        self.action_Clear_all = QtGui.QAction(MainWindow)
        self.action_Clear_all.setObjectName("action_Clear_all")
        self.action_Clear_All = QtGui.QAction(MainWindow)
        self.action_Clear_All.setObjectName("action_Clear_All")
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Window.addAction(self.action_Clear_All)
        self.menu_Aerodynamics.addAction(self.action_Potential_Flows)
        self.menu_Aerodynamics.addAction(self.actionPanel_Methods)
        self.menu_Aerodynamics.addAction(self.actionCFD)
        self.menu_Aerodynamics.addSeparator()
        self.menu_Aerodynamics.addAction(self.action_Clear_all)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Aerodynamics.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.label_X.setBuddy(self.doubleSpinBox_X)
        self.label_Y.setBuddy(self.doubleSpinBox_Y)
        self.label_FlowAngle.setBuddy(self.doubleSpinBox_FlowAngle)
        self.label_Strength.setBuddy(self.doubleSpinBox_Strength)
        self.label_patchInfo1.setBuddy(self.doubleSpinBox_patchInfo1)
        self.label_patchInfo2.setBuddy(self.doubleSpinBox_patchInfo2)

        self.retranslateUi(MainWindow)
        self.tabWidget_potInput.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.actionCFD, QtCore.SIGNAL("activated()"), self.Input_Dock.show)
        QtCore.QObject.connect(self.actionCFD, QtCore.SIGNAL("activated()"), self.Input_Dock.setFocus)
        QtCore.QObject.connect(self.action_Potential_Flows, QtCore.SIGNAL("activated()"), self.Input_Dock.show)
        QtCore.QObject.connect(self.action_Potential_Flows, QtCore.SIGNAL("activated()"), self.Input_Dock.setFocus)
        QtCore.QObject.connect(self.actionPanel_Methods, QtCore.SIGNAL("activated()"), self.Input_Dock.show)
        QtCore.QObject.connect(self.actionPanel_Methods, QtCore.SIGNAL("activated()"), self.Input_Dock.setFocus)
        QtCore.QObject.connect(self.radioButton_PathLines, QtCore.SIGNAL("clicked()"), self.frame_patchInput.show)
        QtCore.QObject.connect(self.radioButton_StreamLines, QtCore.SIGNAL("clicked()"), self.frame_patchInput.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_Source, self.radioButton_Sink)
        MainWindow.setTabOrder(self.radioButton_Sink, self.radioButton_Doublet)
        MainWindow.setTabOrder(self.radioButton_Doublet, self.radioButton_Vortex)
        MainWindow.setTabOrder(self.radioButton_Vortex, self.radioButton_UniformFlow)
        MainWindow.setTabOrder(self.radioButton_UniformFlow, self.doubleSpinBox_X)
        MainWindow.setTabOrder(self.doubleSpinBox_X, self.doubleSpinBox_Y)
        MainWindow.setTabOrder(self.doubleSpinBox_Y, self.doubleSpinBox_FlowAngle)
        MainWindow.setTabOrder(self.doubleSpinBox_FlowAngle, self.doubleSpinBox_Strength)
        MainWindow.setTabOrder(self.doubleSpinBox_Strength, self.pushButton_Clear)
        MainWindow.setTabOrder(self.pushButton_Clear, self.pushButton_Add)
        MainWindow.setTabOrder(self.pushButton_Add, self.pushButton_Simulate)
        MainWindow.setTabOrder(self.pushButton_Simulate, self.pushButton_toggleSimulation)
        MainWindow.setTabOrder(self.pushButton_toggleSimulation, self.pushButton_Remove)
        MainWindow.setTabOrder(self.pushButton_Remove, self.pushButton_Edit)
        MainWindow.setTabOrder(self.pushButton_Edit, self.treeWidget_potElements)
        MainWindow.setTabOrder(self.treeWidget_potElements, self.tabWidget_potInput)
        MainWindow.setTabOrder(self.tabWidget_potInput, self.radioButton_PathLines)
        MainWindow.setTabOrder(self.radioButton_PathLines, self.radioButton_StreamLines)
        MainWindow.setTabOrder(self.radioButton_StreamLines, self.comboBox_pathLines)
        MainWindow.setTabOrder(self.comboBox_pathLines, self.doubleSpinBox_centerX)
        MainWindow.setTabOrder(self.doubleSpinBox_centerX, self.doubleSpinBox_centerY)
        MainWindow.setTabOrder(self.doubleSpinBox_centerY, self.doubleSpinBox_patchInfo1)
        MainWindow.setTabOrder(self.doubleSpinBox_patchInfo1, self.doubleSpinBox_patchInfo2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EduAeroSpace", None, QtGui.QApplication.UnicodeUTF8))
        self.Input_Dock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Potential flows", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Added Elements", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_potElements.isSortingEnabled()
        self.treeWidget_potElements.setSortingEnabled(False)
        self.treeWidget_potElements.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Doublets", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Sinks", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Uniformflow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "Vortices", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_potElements.setSortingEnabled(__sortingEnabled)
        self.pushButton_Remove.setText(QtGui.QApplication.translate("MainWindow", "&Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Edit.setText(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_toggleSimulation.setText(QtGui.QApplication.translate("MainWindow", "&Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Simulate.setText(QtGui.QApplication.translate("MainWindow", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Source.setText(QtGui.QApplication.translate("MainWindow", "&Source", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Sink.setText(QtGui.QApplication.translate("MainWindow", "S&ink", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Doublet.setText(QtGui.QApplication.translate("MainWindow", "&Doublet", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Vortex.setText(QtGui.QApplication.translate("MainWindow", "&Vortex", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_UniformFlow.setText(QtGui.QApplication.translate("MainWindow", "&Uniform flow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_FlowAngle.setText(QtGui.QApplication.translate("MainWindow", "&Flow angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Strength.setText(QtGui.QApplication.translate("MainWindow", "Strength", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Add.setText(QtGui.QApplication.translate("MainWindow", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_potInput.setTabText(self.tabWidget_potInput.indexOf(self.tab_potInput), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(0, QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(1, QtGui.QApplication.translate("MainWindow", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(2, QtGui.QApplication.translate("MainWindow", "Rectangular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(3, QtGui.QApplication.translate("MainWindow", "Line at X", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(4, QtGui.QApplication.translate("MainWindow", "Line at Y", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(5, QtGui.QApplication.translate("MainWindow", "Elliptical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(6, QtGui.QApplication.translate("MainWindow", "Parabolic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathLines.setItemText(7, QtGui.QApplication.translate("MainWindow", "Hyperbolic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_center.setText(QtGui.QApplication.translate("MainWindow", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_patchInfo1.setText(QtGui.QApplication.translate("MainWindow", "At X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_patchInfo2.setText(QtGui.QApplication.translate("MainWindow", "At Y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_PathLines.setText(QtGui.QApplication.translate("MainWindow", "&Path lines", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_StreamLines.setText(QtGui.QApplication.translate("MainWindow", "&Stream lines", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_potInput.setTabText(self.tabWidget_potInput.indexOf(self.tab_potOutputControl), QtGui.QApplication.translate("MainWindow", "Output Control", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(QtGui.QApplication.translate("MainWindow", "&Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Aerodynamics.setTitle(QtGui.QApplication.translate("MainWindow", "&Aerodynamics", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Icons.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Tools.setText(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Potential_Flows.setText(QtGui.QApplication.translate("MainWindow", "&Potential Flows", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPanel_Methods.setText(QtGui.QApplication.translate("MainWindow", "Panel Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCFD.setText(QtGui.QApplication.translate("MainWindow", "CFD", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clear_all.setText(QtGui.QApplication.translate("MainWindow", "&Clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Clear_All.setText(QtGui.QApplication.translate("MainWindow", "&Clear All", None, QtGui.QApplication.UnicodeUTF8))

